name: Hello World

on:
  push:
    branches:
      - main
      - develop

jobs:
  hello-world:
    runs-on: ubuntu-24.04

    steps:
      - name: Print hello world
        run: echo 'Hello World'

  hello-secret :
    runs-on : ubuntu-24.04

    steps :
      - name : Print Secret
        run : echo '${{secret.MY_SECRET}}'